### ISSUE TITLE
SHA512 failure

### ISSUE THREAD

**Issue by alantech21** [TheNewNormal/coreos-osx#55]
I'm getting the following message while doing initial setup:

Error: SHA512 hash verification failed for coreos_production_pxe_image.cpio.gz

It is consistently reproducible as I've gotten this message every time I try to do a setup.

**Comment by rimusz** [comment]
@AntonioMeireles any idea why it happens?

**Comment by AntonioMeireles** [comment]
OH.. at sight - it looks like they upgraded (again) their signing keys. looking into it. new release in next few hours if that is the case.

**Comment by AntonioMeireles** [comment]
@alantech21 

a few extra questions ... what version/channel are you trying to pull ? are you behind some sort of proxy or firewall ? 

thanks in advance!

**Comment by alantech21** [comment]
I was pulling the stable version. There is a firewall, but I am the administrator for it, so I was able to ensure that that was not the problem. Also, I tried it from home with only simple NATing and the problem persisted. As you pointed out, the keys changed. Could that be the problem? I moved on to the coreos cluster and did not have a problem there.

Alan Townsend

**Comment by AntonioMeireles** [comment]
@alantech21 we 'll get **corectl** v0.5.5 released soonish. that version will have bundled the latest upstream image signing keys. In any case that doesn't seem to be the issue here as i'm able to fetch any CoreOS image set with 0.5.4. Still trying to figure with available data set what could be triggering this as definitively it doesn't seem to be a general issue.

**Comment by rimusz** [comment]
@alantech21 the App v1.2.6 now includes the latest `corectl` v0.5.5, please check it out
